# docker-compose.yml - Compose file to run multiple services
version: '3.8'

services:
  api_gateway:
    build: .
    container_name: api_gateway
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  realtime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtime_service
    ports:
      - "6000:6000"
    environment:
      - FLASK_ENV=production
      - API_HOST=0.0.0.0
      - API_PORT=6000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
